package no.nav.aap.behandlingsflyt.faktagrunnlag

enum class InformasjonskravNavn {
    MELDEKORT,
    BARN,
    YRKESSKADE,
    AKTIVITETSPLIKT,
    FORUTGÅENDE_MEDLEMSKAP,
    INNTEKT,
    LOVVALG,
    SAMORDNING_YTELSE,
    SAMORDNING_TJENESTEPENSJON,
    LEGEERKLÆRING,
    SØKNAD,
    INSTITUSJONSOPPHOLD,
    PERSONOPPLYSNING_FORUTGÅENDE,
    PERSONOPPLYSNING,
    UFØRE,
    RETTIGHETSPERIODE,
    TRUKKET_SØKNAD,
    TRUKKET_KLAGE,
}