[versions]
komponenter = "2.0.157"
tilgang = "1.0.235"
utbetaling = "0.0.135"
brev = "0.0.280"
meldekort = "0.0.237"
apiIntern = "0.0.105"
dokumentinnhenting = "0.0.5"

[libraries]
# Komponenter
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
tidslinje = { module = "no.nav.aap.kelvin:tidslinje", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
gateway = { module = "no.nav.aap.kelvin:gateway", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
motorTestUtils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgangKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
utbetalKontrakt = { module = "no.nav.aap.utbetal:api-kontrakt", version.ref = "utbetaling" }
brevKontrakt = { module = "no.nav.aap.brev:kontrakt", version.ref = "brev" }
meldekortKontrakt = { module = "no.nav.aap.meldekort:kontrakt", version.ref = "meldekort" }
apiInternKontrakt = { module = "no.nav.aap.api.intern:kontrakt", version.ref = "apiIntern" }
dokumentinnhentingKontrakt = { module = "no.nav.aap.dokumentinnhenting:kontrakt", version.ref = "dokumentinnhenting" }
ktorOpenApiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }

bekk-open-nocommons = { module = "no.bekk.bekkopen:nocommons", version = "0.17.0" }