[versions]
komponenter = "2.0.173"
tilgang = "1.0.242"
utbetaling = "0.0.136"
brev = "0.0.290"
meldekort = "0.0.237"
apiIntern = "0.0.111"
dokumentinnhenting = "0.0.7"
arenaoppslag = "0.7.13"

[libraries]
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
tidslinje = { module = "no.nav.aap.kelvin:tidslinje", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
gateway = { module = "no.nav.aap.kelvin:gateway", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
motorTestUtils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgangKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
utbetalKontrakt = { module = "no.nav.aap.utbetal:api-kontrakt", version.ref = "utbetaling" }
brevKontrakt = { module = "no.nav.aap.brev:kontrakt", version.ref = "brev" }
meldekortKontrakt = { module = "no.nav.aap.meldekort:kontrakt", version.ref = "meldekort" }
apiInternKontrakt = { module = "no.nav.aap.api.intern:kontrakt", version.ref = "apiIntern"}
dokumentinnhentingKontrakt = { module = "no.nav.aap.dokumentinnhenting:kontrakt", version.ref = "dokumentinnhenting" }
arenaoppslag-kontrakt = { module = "no.nav.aap.arenaoppslag:kontrakt", version.ref = "arenaoppslag" }

bekk-nocommons = { module = "no.bekk.bekkopen:nocommons", version = "0.17.0" }

ktorOpenApiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }