package no.nav.aap.behandlingsflyt.faktagrunnlag.delvurdering.underveis

enum class UnderveisÅrsak {
    IKKE_GRUNNLEGGENDE_RETT,
    MELDEPLIKT_FRIST_IKKE_PASSERT,
    IKKE_OVERHOLDT_MELDEPLIKT_SANKSJON,
    ARBEIDER_MER_ENN_GRENSEVERDI,
    SONER_STRAFF,
    BRUDD_PÅ_AKTIVITETSPLIKT,
    FRAVÆR_FASTSATT_AKTIVITET,
    VARIGHETSKVOTE_BRUKT_OPP,
}
