package no.nav.aap.behandlingsflyt.behandling.avklaringsbehov.løser

enum class ÅrsakTilSettPåVent {
    VENTER_PÅ_OPPLYSNINGER,
    VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER,
    VENTER_PÅ_MEDISINSKE_OPPLYSNINGER,
    VENTER_PÅ_VURDERING_AV_ROL,
    VENTER_PÅ_SVAR_FRA_BRUKER,
    VENTER_PÅ_MASKINELL_AVKLARING,
    VENTER_PÅ_UTENLANDSK_VIDEREFORING_AVKLARING,
    VENTER_PÅ_KLAGE_IMPLEMENTASJON,
    VENTER_PÅ_SVAR_PÅ_FORHÅNDSVARSEL,
    VENTER_PÅ_FUNKSJONALITET
}
