package no.nav.aap.behandlingsflyt.faktagrunnlag.delvurdering.underveis

enum class UnderveisÅrsak(val konsekvens: Konsekvens) {
    IKKE_GRUNNLEGGENDE_RETT(Konsekvens.KONSEKVENS_FØLGER_AVSLAGSÅRSAK_TIL_RETTIGHETSTYPEN),
    MELDEPLIKT_FRIST_IKKE_PASSERT(Konsekvens.REDUKSJON),
    IKKE_OVERHOLDT_MELDEPLIKT_SANKSJON(Konsekvens.REDUKSJON),
    ARBEIDER_MER_ENN_GRENSEVERDI(Konsekvens.REDUKSJON),
    SONER_STRAFF(Konsekvens.STANS),
    VARIGHETSKVOTE_BRUKT_OPP(Konsekvens.OPPHØR),
    BRUDD_PÅ_AKTIVITETSPLIKT_11_7_STANS(Konsekvens.STANS),
    BRUDD_PÅ_AKTIVITETSPLIKT_11_7_OPPHØR(Konsekvens.OPPHØR),
    BRUDD_PÅ_OPPHOLDSKRAV_11_3_STANS(Konsekvens.STANS),
    BRUDD_PÅ_OPPHOLDSKRAV_11_3_OPPHØR(Konsekvens.OPPHØR),
}

enum class Konsekvens {
    KONSEKVENS_FØLGER_AVSLAGSÅRSAK_TIL_RETTIGHETSTYPEN,
    STANS,
    OPPHØR,
    REDUKSJON,
}