ALTER TABLE FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING
    ADD COLUMN VURDERT_AV varchar(50) NOT NULL DEFAULT 'Ukjent';

ALTER TABLE FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING
    ALTER COLUMN VURDERT_AV DROP DEFAULT;