ALTER TABLE STUDENT_VURDERING
    ADD COLUMN VURDERT_AV varchar(50) NOT NULL DEFAULT 'Ukjent';

ALTER TABLE STUDENT_VURDERING
    ADD COLUMN VURDERT_TIDSPUNKT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE STUDENT_VURDERING
    ALTER COLUMN VURDERT_AV DROP DEFAULT;