DROP INDEX IDX_MELDEPLIKT_RIMELIG_GRUNN_GRUNNLAG_BEHANDLING_ID;
DROP INDEX IDX_MELDEPLIKT_RIMELIG_GRUNN_VURDERING_MELDEPLIKT_ID;

DROP TABLE MELDEPLIKT_RIMELIG_GRUNN_GRUNNLAG;
DROP TABLE MELDEPLIKT_RIMELIG_GRUNN_VURDERING;
DROP TABLE MELDEPLIKT_RIMELIG_GRUNN;

CREATE TABLE MELDEPLIKT_OVERSTYRING_GRUNNLAG
(
    ID                                    BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                         BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    OPPRETTET_TID                         TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AKTIV                                 BOOLEAN                                NOT NULL
);

CREATE UNIQUE INDEX IDX_MELDEPLIKT_OVERSTYRING_GRUNNLAG_BEHANDLING_ID ON MELDEPLIKT_OVERSTYRING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE MELDEPLIKT_OVERSTYRING_VURDERING
(
    ID                                    BIGSERIAL                              NOT NULL PRIMARY KEY,
    VURDERT_I_BEHANDLING                  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERT_AV                            TEXT                                   NOT NULL,
    OPPRETTET_TID                         TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE MELDEPLIKT_OVERSTYRING_VURDERINGER
(
    GRUNNLAG_ID                   BIGSERIAL              NOT NULL REFERENCES MELDEPLIKT_OVERSTYRING_GRUNNLAG (ID),
    VURDERING_ID                  BIGSERIAL              NOT NULL REFERENCES MELDEPLIKT_OVERSTYRING_VURDERING (ID)
);

CREATE INDEX IDX_MELDEPLIKT_OVERSTYRING_VURDERINGER_GRUNNLAG_ID ON MELDEPLIKT_OVERSTYRING_VURDERINGER (GRUNNLAG_ID);


CREATE TABLE MELDEPLIKT_OVERSTYRING_VURDERING_PERIODER
(
    ID                                  BIGSERIAL                              NOT NULL PRIMARY KEY,
    MELDEPLIKT_OVERSTYRING_VURDERING_ID BIGINT                                 NOT NULL REFERENCES MELDEPLIKT_OVERSTYRING_VURDERING (ID),
    MELDEPLIKT_OVERSTYRING_STATUS       TEXT                                   NOT NULL,
    PERIODE                             DATERANGE                              NOT NULL,
    BEGRUNNELSE                         TEXT                                   NOT NULL,
    OPPRETTET_TID                       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_MELDEPLIKT_OVERSTYRING_VURDERING_PERIODER_ID ON MELDEPLIKT_OVERSTYRING_VURDERING_PERIODER (MELDEPLIKT_OVERSTYRING_VURDERING_ID);
