CREATE TABLE REFUSJONKRAV_VURDERINGER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE REFUSJONKRAV_VURDERING
    ADD column refusjonkrav_vurderinger_id BIGINT NULL REFERENCES REFUSJONKRAV_VURDERINGER (ID);

ALTER TABLE REFUSJONKRAV_GRUNNLAG
    ADD COLUMN refusjonkrav_vurderinger_id BIGINT REFERENCES REFUSJONKRAV_VURDERINGER (ID);

ALTER TABLE REFUSJONKRAV_GRUNNLAG
    ALTER column refusjonkrav_vurdering_id DROP NOT NULL;


CREATE UNIQUE INDEX UIDX_REFUSJONKRAV_GRUNNLAG_HISTORIKK ON REFUSJONKRAV_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

