CREATE TABLE MELDEPLIKT_RIMELIG_GRUNN
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE MELDEPLIKT_RIMELIG_GRUNN_VURDERING
(
    ID                          BIGSERIAL                              NOT NULL PRIMARY KEY,
    MELDEPLIKT_RIMELIG_GRUNN_ID BIGINT                                 NOT NULL REFERENCES MELDEPLIKT_RIMELIG_GRUNN (ID),
    BEGRUNNELSE                 TEXT                                   NOT NULL,
    VURDERT_AV                  TEXT                                   NOT NULL,
    HAR_RIMELIG_GRUNN           BOOLEAN                                NOT NULL,
    FRA_DATO                    DATE                                   NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_MELDEPLIKT_RIMELIG_GRUNN_VURDERING_MELDEPLIKT_ID ON MELDEPLIKT_RIMELIG_GRUNN_VURDERING (MELDEPLIKT_RIMELIG_GRUNN_ID);

CREATE TABLE MELDEPLIKT_RIMELIG_GRUNN_GRUNNLAG
(
    ID                          BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID               BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    MELDEPLIKT_RIMELIG_GRUNN_ID BIGINT                                 NOT NULL REFERENCES MELDEPLIKT_RIMELIG_GRUNN (ID),
    AKTIV                       BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_MELDEPLIKT_RIMELIG_GRUNN_GRUNNLAG_BEHANDLING_ID ON MELDEPLIKT_RIMELIG_GRUNN_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);


