CREATE TABLE TJENESTEPENSJON_YTELSER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TJENESTEPENSJON_GRUNNLAG
(
    ID                         BIGSERIAL PRIMARY KEY,
    AKTIV                      bool                                   NOT NULL,
    BEHANDLING_ID              BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    OPPRETTET_TID              TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TJENESTEPENSJON_YTELSER_ID BIGINT                                 NOT NULL REFERENCES TJENESTEPENSJON_YTELSER (ID)

);

CREATE TABLE TJENESTEPENSJON_YTELSE
(
    ID                         BIGSERIAL PRIMARY KEY,
    TJENESTEPENSJON_YTELSER_ID BIGINT NOT NULL REFERENCES TJENESTEPENSJON_YTELSER (ID),
    TP_NUMMER                  TEXT   NOT NULL
);

CREATE INDEX IDX_TJENESTEPENSJON_ENTRIES ON TJENESTEPENSJON_YTELSE (ID);