CREATE TABLE SYKDOM_VURDERING_BREV
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID        BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AKTIV                BOOLEAN DEFAULT TRUE                   NOT NULL,
    VURDERING            TEXT                                   NULL,
    VURDERT_AV           TEXT DEFAULT 'Ukjent'                  NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_SYKDOM_VURDERING_BREV_BEHANDLING_ID ON SYKDOM_VURDERING_BREV (BEHANDLING_ID) WHERE (AKTIV = TRUE);