ALTER TABLE SYKEPENGE_VURDERING
    ADD COLUMN VURDERT_AV TEXT NOT NULL DEFAULT 'Ukjent';

ALTER TABLE SYKEPENGE_VURDERING
    ADD COLUMN OPPRETTET_TID TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE SYKEPENGE_VURDERING
    ALTER COLUMN VURDERT_AV DROP DEFAULT;