ALTER TABLE MEDLEMSKAP_UNNTAK
    ADD COLUMN KILDESYSTEM varchar(50) NULL,
    ADD COLUMN KILDENAVN varchar(50) NULL;

ALTER TABLE MEDLEMSKAP_FORUTGAAENDE_UNNTAK
    ADD COLUMN KILDESYSTEM varchar(50) NULL,
    ADD COLUMN KILDENAVN varchar(50) NULL;