ALTER TABLE PERSONOPPLYSNING_FORUTGAAENDE_GRUNNLAG
    DROP COLUMN PERSONOPPLYSNINGER_ID;

DROP INDEX UIDX_PERSONOPPLYSNING_FORUTGAAENDE;
DROP TABLE PERSONOPPLYSNING_FORUTGAAENDE;
DROP TABLE PERSONOPPLYSNINGER_FORUTGAAENDE;