CREATE TABLE SONINGSFORHOLD_GRUNNLAG
(
    ID                                     BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                          BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SONING_UTENFOR_FENGSEL                 BOOLEAN                                NOT NULL,
    BEGRUNNELSE_FOR_SONING_UTENFOR_FENGSEL TEXT,
    ARBEID_UTENFOR_ANSALT                  BOOLEAN,
    BEGRUNNELSE_FOR_SONING_UTENFOR_ANSTALT TEXT,
    AKTIV                                  BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID                          TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_SONINGSFORHOLD_GRUNNLAG_HISTORIKK ON SONINGSFORHOLD_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
