-- Forutgaande medlemskap
-- Aggerat
CREATE TABLE BRUKER_UTENLANDSADRESSER_FORUTGAAENDE_AGGREGAT(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BRUKER_UTENLANDSADRESSE_FORUTGAAENDE(
    ID                      BIGSERIAL    NOT NULL PRIMARY KEY,
    ADRESSENAVN             VARCHAR(150) NULL,
    POSTKODE                VARCHAR(25)  NULL,
    BYSTED                  VARCHAR(50)  NULL,
    LANDKODE                VARCHAR(10)  NULL,
    GYLDIGFRAOGMED          DATE NULL,
    GYLDIGTILOGMED          DATE NULL,
    UTENLANDSADRESSER_ID    BIGINT       NOT NULL REFERENCES BRUKER_UTENLANDSADRESSER_FORUTGAAENDE_AGGREGAT(ID),
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_BRUKER_FORUTGAAENDE_UTENLANDSADRESSER_ID ON BRUKER_UTENLANDSADRESSE_FORUTGAAENDE (UTENLANDSADRESSER_ID);

ALTER TABLE BRUKER_PERSONOPPLYSNING_FORUTGAAENDE
    ADD COLUMN UTENLANDSADRESSER_ID BIGINT NULL REFERENCES BRUKER_UTENLANDSADRESSER_FORUTGAAENDE_AGGREGAT(ID);

-- Lovvalg og medlemskap
-- Aggerat
CREATE TABLE BRUKER_UTENLANDSADRESSER_AGGREGAT(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BRUKER_UTENLANDSADRESSE(
    ID                      BIGSERIAL    NOT NULL PRIMARY KEY,
    ADRESSENAVN             VARCHAR(150) NULL,
    POSTKODE                VARCHAR(25)  NULL,
    BYSTED                  VARCHAR(50)  NULL,
    LANDKODE                VARCHAR(10)  NULL,
    GYLDIGFRAOGMED          DATE NULL,
    GYLDIGTILOGMED          DATE NULL,
    UTENLANDSADRESSER_ID    BIGINT      NOT NULL REFERENCES BRUKER_UTENLANDSADRESSER_AGGREGAT(ID),
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_LOVVALG_UTENLANDSADRESSER_ID ON BRUKER_UTENLANDSADRESSE (UTENLANDSADRESSER_ID);

ALTER TABLE BRUKER_PERSONOPPLYSNING
    ADD COLUMN UTENLANDSADRESSER_ID BIGINT NULL REFERENCES BRUKER_UTENLANDSADRESSER_AGGREGAT(ID);