CREATE TABLE OPPFOLGINGSOPPGAVE_VURDERING
(
    ID                           BIGSERIAL PRIMARY KEY,
    KONSEKVENS_AV_OPPFOLGING     TEXT,
    OPPLYSNINGER_TIL_REVURDERING TEXT[],
    AARSAK_TIL_REVURDERING       TEXT,
    VURDERT_AV                   TEXT
);


CREATE TABLE OPPFOLGINGSOPPGAVE_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERING_ID  BIGINT                                 NULL REFERENCES OPPFOLGINGSOPPGAVE_VURDERING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_OPPFOLGINGSOPPGAVE_GRUNNLAG_BEHANDLING_ID
    ON OPPFOLGINGSOPPGAVE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
