CREATE TABLE SAMORDNING_UFORE_VURDERING
(
    ID             BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING,
    BEGRUNNELSE    TEXT                                   NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AKTIV          BOOLEAN      DEFAULT TRUE              NOT NULL
);

CREATE UNIQUE INDEX UIDX_SAMORDNING_UFORE_VURDERING_BEHANDLING_ID
    ON SAMORDNING_UFORE_VURDERING (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE SAMORDING_UFORE_VURDERING_PERIODE
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VURDERING_ID  BIGINT                                 NOT NULL REFERENCES SAMORDNING_UFORE_VURDERING,
    PERIODE       DATERANGE                              NOT NULL,
    UFOREGRAD     SMALLINT                               NOT NULL
);
