DROP TABLE BARN_VURDERING CASCADE;
DROP TABLE BARN_VURDERING_PERIODE CASCADE;

CREATE TABLE BARN_VURDERING_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES BARN_VURDERING_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BARN_VURDERING_PERIODE
    ADD CONSTRAINT BARN_VURDERING_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
        );


CREATE TABLE BARN_VURDERING
(
    ID                        BIGSERIAL   NOT NULL PRIMARY KEY,
    IDENT                     VARCHAR(19) NOT NULL,
    BARN_VURDERING_PERIODE_ID BIGINT      NOT NULL REFERENCES BARN_VURDERING_PERIODE (ID)
);

