ALTER TABLE AARSAK_TIL_BEHANDLING
    RENAME TO VURDERINGSBEHOV;

ALTER INDEX IDX_AARSAK_TIL_BEHANDLING_TID RENAME TO IDX_VURDERINGSBEHOV_TID;
ALTER INDEX UIDX_AARSAK_TIL_BEHANDLING RENAME TO UIDX_VURDERINGSBEHOV;
