CREATE TABLE OVERGANG_UFORE_VURDERINGER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE OVERGANG_UFORE_VURDERING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEGRUNNELSE              TEXT                                   NOT NULL,
    BRUKER_SOKT_UFORETRYGD   BOOLEAN      DEFAULT FALSE             NOT NULL,
    BRUKER_VEDTAK_UFORETRYGD TEXT                                   NULL,
    BRUKER_RETT_PAA_AAP      BOOLEAN      DEFAULT FALSE             NOT NULL,
    VURDERT_AV varchar(50) NOT NULL DEFAULT 'Ukjent',
    VURDERINGEN_GJELDER_FRA DATE                               NOT NULL,
    VIRKNINGSDATO       DATE                                   NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VURDERINGER_ID BIGINT NULL REFERENCES OVERGANG_UFORE_VURDERINGER (ID)
);


CREATE TABLE OVERGANG_UFORE_GRUNNLAG
(
    ID                       BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID            BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERINGER_ID           BIGINT NULL REFERENCES OVERGANG_UFORE_VURDERINGER (ID),
    AKTIV                    BOOLEAN DEFAULT TRUE                   NOT NULL,
    OPPRETTET_TID            TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);