-- Aggerat
CREATE TABLE BRUKER_LAND_AGGREGAT(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Opprett nye tabeller for støtte av flere statsborgerskap
CREATE TABLE BRUKER_LAND(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    LAND            VARCHAR(50)  DEFAULT 'XUK' NOT NULL,
    GYLDIGFRAOGMED  DATE NULL,
    GYLDIGTILOGMED  DATE NULL,
    LANDKODER_ID    BIGINT       NULL REFERENCES BRUKER_LAND_AGGREGAT(ID),
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_BRUKER_LAND_LOVVALG_LANDKODER_ID ON BRUKER_LAND (LANDKODER_ID);

ALTER TABLE BRUKER_PERSONOPPLYSNING
    ADD COLUMN LANDKODER_ID BIGINT NULL REFERENCES BRUKER_LAND_AGGREGAT(ID);