CREATE TABLE SAMORDNING_ANDRE_STATLIGE_YTELSER_VURDERING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEGRUNNELSE   TEXT                                   NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VURDERT_AV    VARCHAR(50)                            NOT NULL
);

CREATE TABLE SAMORDNING_ANDRE_STATLIGE_YTELSER_VURDERING_PERIODE
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VURDERING_ID  BIGINT                                 NOT NULL REFERENCES SAMORDNING_ANDRE_STATLIGE_YTELSER_VURDERING (ID),
    PERIODE       DATERANGE                              NOT NULL,
    YTELSE_TYPE   VARCHAR(50)                            NOT NULL,
    BELOP         SMALLINT                               NOT NULL
);

CREATE TABLE SAMORDNING_ANDRE_STATLIGE_YTELSER_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERING_ID  BIGINT                                 NULL REFERENCES SAMORDNING_ANDRE_STATLIGE_YTELSER_VURDERING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_SAMORDNING_ANDRE_STATLIGE_YTELSER_GRUNNLAG_BEHANDLING_ID
    ON SAMORDNING_ANDRE_STATLIGE_YTELSER_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
