CREATE TABLE MANUELL_INNTEKT_VURDERINGER
(
    ID            BIGSERIAL      NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MANUELL_INNTEKT_VURDERING
(
    ID                              BIGSERIAL      NOT NULL PRIMARY KEY,
    AR                              SMALLINT       NOT NULL,
    BEGRUNNELSE                     TEXT           NOT NULL,
    BELOP                           NUMERIC(19, 2) NOT NULL,
    VURDERT_AV                      VARCHAR(50)    NOT NULL DEFAULT 'Ukjent',
    MANUELL_INNTEKT_VURDERINGER_ID  BIGINT         NOT NULL REFERENCES MANUELL_INNTEKT_VURDERINGER (ID),
    OPPRETTET_TID                   TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_MANUELL_INNTEKT_VURDERINGER_ID ON MANUELL_INNTEKT_VURDERING (MANUELL_INNTEKT_VURDERINGER_ID);

CREATE TABLE MANUELL_INNTEKT_VURDERING_GRUNNLAG(
    ID                              BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SAK_ID                          BIGINT                                 NOT NULL REFERENCES SAK (ID),
    MANUELL_INNTEKT_VURDERINGER_ID  BIGINT                                 NOT NULL REFERENCES MANUELL_INNTEKT_VURDERINGER (ID),
    AKTIV                           BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID                   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_INNTEKT_VURDERING_GRUNNLAG_BEHANDLING_ID ON MANUELL_INNTEKT_VURDERING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);