CREATE TABLE SAMORDNING_ARBEIDSGIVER_VURDERING_PERIODE(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VURDERING_ID  BIGINT                                 NOT NULL REFERENCES SAMORDNING_ARBEIDSGIVER_VURDERING (ID),
    FOM           DATE                                   NOT NULL,
    TOM           DATE                                   NOT NULL,
);