CREATE TABLE ARBEIDSOPPTRAPPING_VURDERINGER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ARBEIDSOPPTRAPPING_GRUNNLAG
(
    ID             BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERINGER_ID BIGINT                                 NULL REFERENCES ARBEIDSOPPTRAPPING_VURDERINGER (ID),
    AKTIV          BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IDX_ARBEIDSOPPTRAPPING_GRUNNLAG_BEHANDLING_ID ON ARBEIDSOPPTRAPPING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE ARBEIDSOPPTRAPPING_VURDERING
(
    ID                          BIGSERIAL PRIMARY KEY,
    BEGRUNNELSE                 TEXT                                   NOT NULL,
    MULIGHET_TIL_OPPTRAPPING    BOOLEAN                                NOT NULL,
    RETT_PAA_AAP                BOOLEAN                                NOT NULL,
    VURDERINGER_ID              BIGINT                                 NOT NULL REFERENCES ARBEIDSOPPTRAPPING_VURDERINGER (ID),
    VURDERT_AV                  varchar(50)                            NOT NULL,
    GJELDER_FRA                 DATE                                   NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_ARBEIDSOPPTRAPPING_VURDERING_VURDERINGER_ID ON ARBEIDSOPPTRAPPING_VURDERING (VURDERINGER_ID);