ALTER TABLE YRKESSKADE_DATO
    ADD COLUMN VEDTAKSDATO              DATE,
    ADD COLUMN SKADEART                 TEXT,
    ADD COLUMN DIAGNOSE                 TEXT,
    ADD COLUMN SKADEKOMBINASJONER       TEXT,
    ADD COLUMN SKADEKOMBINASJONER_TEKST TEXT;
