CREATE TABLE LOVVALG_MEDLEMSKAP_MANUELL_VURDERINGER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE LOVVALG_MEDLEMSKAP_MANUELL_VURDERING
    ADD COLUMN VURDERINGER_ID       BIGINT REFERENCES LOVVALG_MEDLEMSKAP_MANUELL_VURDERINGER,
    ADD COLUMN VURDERT_I_BEHANDLING BIGINT REFERENCES BEHANDLING (ID),
    ADD COLUMN FOM                  DATE,
    ADD COLUMN TOM                  DATE;

ALTER TABLE MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG
    ADD COLUMN VURDERINGER_ID BIGINT REFERENCES LOVVALG_MEDLEMSKAP_MANUELL_VURDERINGER;
