CREATE TABLE OPPHOLDSKRAV_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AKTIV         BOOLEAN                                NOT NULL
);

CREATE UNIQUE INDEX IDX_OPPHOLDSKRAV_GRUNNLAG_BEHANDLING_ID ON OPPHOLDSKRAV_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE OPPHOLDSKRAV_VURDERING
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    VURDERT_I_BEHANDLING BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERT_AV           TEXT                                   NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE OPPHOLDSKRAV_VURDERINGER
(
    GRUNNLAG_ID  BIGSERIAL NOT NULL REFERENCES OPPHOLDSKRAV_GRUNNLAG (ID),
    VURDERING_ID BIGSERIAL NOT NULL REFERENCES OPPHOLDSKRAV_VURDERING (ID)
);

CREATE INDEX IDX_OPPHOLDSKRAV_VURDERINGER_GRUNNLAG_ID ON OPPHOLDSKRAV_VURDERINGER (GRUNNLAG_ID);


CREATE TABLE OPPHOLDSKRAV_VURDERING_PERIODE
(
    ID                        BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPHOLDSKRAV_VURDERING_ID BIGINT                                 NOT NULL REFERENCES OPPHOLDSKRAV_VURDERING (ID),
    OPPRETTET_TID             TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOM                       DATE                                   NOT NULL,
    TOM                       DATE,
    BEGRUNNELSE               TEXT                                   NOT NULL,
    OPPFYLT                   BOOLEAN                                NOT NULL,
    LAND                      TEXT
);

CREATE INDEX IDX_OPPHOLDSKRAV_VURDERING_PERIODE_ID ON OPPHOLDSKRAV_VURDERING_PERIODE (OPPHOLDSKRAV_VURDERING_ID);
