ALTER TABLE MELDEKORT ADD COLUMN begrunnelse TEXT;
ALTER TABLE MELDEKORT ADD COLUMN opprettet_av TEXT;
ALTER TABLE MELDEKORT ADD COLUMN referanse_type TEXT NOT NULL DEFAULT 'JOURNALPOST';
ALTER TABLE MELDEKORT RENAME COLUMN journalpost TO referanse;

DROP INDEX idx_meldekort;
CREATE INDEX idx_meldekort ON meldekort (referanse);
