ALTER TABLE YRKESSKADE_DATO
    ADD COLUMN VEDTAKSDATO                DATE,
    ADD COLUMN SKADEART                   TEXT,
    ADD COLUMN DIAGNOSE                   TEXT,
    ADD COLUMN SKADEKOMBINASJONER         TEXT,
    ADD COLUMN SKADEKOMBINASJONER_TEKST   TEXT,
    ADD COLUMN OPPRETTET_TID              TIMESTAMP(3);

ALTER TABLE YRKESSKADE_GRUNNLAG
    ADD COLUMN OPPGITT_YRKESSKADE_I_SOKNAD BOOLEAN NULL;

ALTER TABLE YRKESSKADE_GRUNNLAG
    ALTER COLUMN YRKESSKADE_ID DROP NOT NULL;
