ALTER TABLE TILBAKEKREVINGSBEHANDLING
ALTER COLUMN VARSEL_SENDT TYPE DATE
        USING VARSEL_SENDT::date;

ALTER TABLE TILBAKEKREVINGSHENDELSE
    ALTER COLUMN VARSEL_SENDT TYPE DATE
        USING VARSEL_SENDT::date;