CREATE TABLE INNTEKT_PERIODE
(
    ID         BIGSERIAL      NOT NULL PRIMARY KEY,
    INNTEKT_ID BIGINT         NOT NULL REFERENCES INNTEKTER (ID),
    PERIODE    daterange      not null,
    BELOP      NUMERIC(19, 2) NOT NULL
);