ALTER TABLE YRKESSKADE_DATO
    ADD COLUMN VEDTAKSDATO              DATE,
    ADD COLUMN SKADEART                 TEXT,
    ADD COLUMN DIAGNOSE                 TEXT,
    ADD COLUMN SKADEKOMBINASJONER       TEXT,
    ADD COLUMN SKADEKOMBINASJONER_TEKST TEXT;

ALTER TABLE YRKESSKADE_GRUNNLAG ADD COLUMN OPPGITT_YRKESSKADE_I_SOKNAD BOOLEAN NOT NULL DEFAULT FALSE;