CREATE TABLE DAGPENGER_PERIODER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE DAGPENGER_GRUNNLAG
(
    ID                    BIGSERIAL PRIMARY KEY,
    AKTIV                 bool                                   NOT NULL,
    BEHANDLING_ID         BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    DAGPENGER_PERIODER_ID BIGINT                                 NOT NULL REFERENCES DAGPENGER_PERIODER (ID),
    OPPRETTET_TID         TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uniq_active_grunnlag_per_behandling
    ON DAGPENGER_GRUNNLAG (BEHANDLING_ID)
    WHERE AKTIV = TRUE;

CREATE TABLE DAGPENGER_PERIODE
(
    ID                    BIGSERIAL PRIMARY KEY,
    DAGPENGER_PERIODER_ID BIGINT    NOT NULL REFERENCES DAGPENGER_PERIODER (ID),
    PERIODE               daterange NOT NULL,
    YTELSE_TYPE           TEXT      NOT NULL,
    KILDE                 TEXT      NOT NULL
)
