ALTER TABLE HELSEOPPHOLD_VURDERING
    ADD COLUMN OPPHOLD_ID           BIGINT REFERENCES OPPHOLD (ID) NULL,
    ADD COLUMN VURDERT_I_BEHANDLING BIGINT REFERENCES BEHANDLING (ID) NULL,
    ADD COLUMN VURDERT_AV           varchar(50) NOT NULL DEFAULT 'Ukjent';

-- Sett vurdert_av for eksisterende rader
UPDATE HELSEOPPHOLD_VURDERING hv
SET VURDERT_AV = hvs.VURDERT_AV
FROM HELSEOPPHOLD_VURDERINGER hvs
WHERE hv.HELSEOPPHOLD_VURDERINGER_ID = hvs.ID;

ALTER TABLE HELSEOPPHOLD_VURDERING
    ALTER COLUMN VURDERT_AV DROP DEFAULT;

