CREATE TABLE TILTAKSPENGER_PERIODER
(
    ID            BIGSERIAL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TILTAKSPENGER_GRUNNLAG
(
    ID                    BIGSERIAL PRIMARY KEY,
    AKTIV                 bool         DEFAULT TRUE              NOT NULL,
    BEHANDLING_ID         BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    TILTAKSPENGER_PERIODER_ID BIGINT                             NOT NULL REFERENCES TILTAKSPENGER_PERIODER (ID),
    OPPRETTET_TID         TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uniq_active_tiltakspenger_grunnlag_per_behandling
    ON TILTAKSPENGER_GRUNNLAG (BEHANDLING_ID)
    WHERE AKTIV = TRUE;

CREATE TABLE TILTAKSPENGER_PERIODE
(
    ID                    BIGSERIAL PRIMARY KEY,
    TILTAKSPENGER_PERIODER_ID BIGINT    NOT NULL REFERENCES TILTAKSPENGER_PERIODER (ID),
    PERIODE               daterange NOT NULL,
    YTELSE_TYPE           TEXT      NOT NULL,
    KILDE                 TEXT      NOT NULL
)
