DROP TABLE ANDRE_YTELSE_OPPGITT_I_SØKNAD;
DROP TABLE ANDRE_YTELSER_OPPGITT_I_SØKNAD_GRUNNLAG;
DROP TABLE ANDRE_YTELSER_SVAR_I_SØKNAD;

CREATE TABLE ANDRE_YTELSER_SVAR_I_SOKNAD
(
    id            BIGSERIAL PRIMARY KEY,
    opprettet_tid TIMESTAMP(3) DEFAULT current_timestamp NOT NULL,
    ekstraLonn    BOOLEAN                                NOT NULL,
    afpKilder     TEXT
);

CREATE TABLE ANNEN_YTELSE_OPPGITT_I_SOKNAD
(
    id               BIGSERIAL PRIMARY KEY,
    andre_ytelser_id BIGINT NOT NULL REFERENCES ANDRE_YTELSER_SVAR_I_SOKNAD (id),
    ytelse           TEXT   NOT NULL
);

CREATE TABLE ANDRE_YTELSER_OPPGITT_I_SOKNAD_GRUNNLAG
(
    id               BIGSERIAL PRIMARY KEY,
    behandling_id    BIGINT               NOT NULL REFERENCES behandling (id),
    andre_ytelser_id BIGINT REFERENCES ANDRE_YTELSER_SVAR_I_SOKNAD (id),
    aktiv            BOOLEAN DEFAULT TRUE NOT NULL
);