CREATE TABLE JOBB_TILLEGGSINFO
(
    JOBB_ID       BIGINT PRIMARY KEY NOT NULL REFERENCES JOBB (ID),
    PAYLOAD       JSONB              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3)       NOT NULL,
    OPPDATERT_TID TIMESTAMP(3)       NOT NULL
);

CREATE INDEX IDX_JOBB_TILLEGGSINFO_JOBB_ID ON JOBB_TILLEGGSINFO (JOBB_ID);
