ALTER TABLE HELSEINSTITUSJON_VURDERING
    ADD COLUMN periode DATERANGE
        NOT NULL
        DEFAULT daterange('2000-01-01', '2000-01-01');

ALTER TABLE HELSEINSTITUSJON_VURDERING
    ALTER COLUMN periode DROP DEFAULT;

ALTER TABLE SONINGSFORHOLD_VURDERING
    ADD COLUMN periode DATERANGE
        NOT NULL
        DEFAULT daterange('2000-01-01', '2000-01-01');

ALTER TABLE SONINGSFORHOLD_VURDERING
    ALTER COLUMN periode DROP DEFAULT;