ALTER TABLE MANUELL_INNTEKT_VURDERING
    ADD COLUMN PERIODE_FOM DATE,
    ADD COLUMN PERIODE_TOM DATE;

DROP INDEX UIDX_MANUELL_INNTEKT_VURDERING;
CREATE UNIQUE INDEX UIDX_MANUELL_INNTEKT_VURDERING
    ON MANUELL_INNTEKT_VURDERING (MANUELL_INNTEKT_VURDERINGER_ID, AR, PERIODE_FOM) NULLS NOT DISTINCT;