ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN FASE TEXT NULL;

ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER BOOLEAN NULL;

-- backfill: eksisterende oppstartsdata får fase OPPSTART
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING v
SET FASE = 'OPPSTART'
WHERE v.EGEN_VIRKSOMHET_OPPSTART_PERIODER_ID IS NOT NULL
  AND v.FASE IS NULL;

-- backfill: eksisterende utviklingsdata får fase UTVIKLING
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING v
SET FASE = 'UTVIKLING'
WHERE v.EGEN_VIRKSOMHET_UTVIKLING_PERIODER_ID IS NOT NULL
  AND v.FASE IS NULL;

-- eksisterende oppstartsbedrifter skal settes til true
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING
SET ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER = TRUE
WHERE FASE = 'OPPSTART'
  AND ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER IS NULL;

-- utvikling skal være null
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING
SET ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER = NULL
WHERE FASE = 'UTVIKLING'
  AND ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER IS NULL;

-- senere:
-- ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
--     ALTER COLUMN FASE SET NOT NULL;