CREATE TABLE ARENA_MIGRERING (
    ID               BIGSERIAL    NOT NULL PRIMARY KEY,
    SAK_ID           BIGINT       NOT NULL UNIQUE REFERENCES SAK (ID),
    SAKSNUMMER_ARENA VARCHAR(50)  NOT NULL,
    IDENT            VARCHAR(19)  NOT NULL,
    MIGRERT_TID      TIMESTAMP(3) NOT NULL
);
