ALTER TABLE PERSON_IDENT
    ADD COLUMN OPPRETTET_TID TIMESTAMP(3),
    ADD COLUMN OPPDATERT_TID TIMESTAMP(3);

UPDATE PERSON_IDENT pi
SET OPPRETTET_TID = COALESCE(
        (SELECT MIN(s.OPPRETTET_TID) FROM SAK s WHERE s.PERSON_ID = pi.PERSON_ID),
        CURRENT_TIMESTAMP
    ),
    OPPDATERT_TID = COALESCE(
        (SELECT MIN(s.OPPRETTET_TID) FROM SAK s WHERE s.PERSON_ID = pi.PERSON_ID),
        CURRENT_TIMESTAMP
    );

ALTER TABLE PERSON_IDENT
    ALTER COLUMN OPPRETTET_TID SET NOT NULL,
    ALTER COLUMN OPPDATERT_TID SET NOT NULL,
    ALTER COLUMN OPPDATERT_TID SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN OPPRETTET_TID SET DEFAULT CURRENT_TIMESTAMP;
