ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN FASE TEXT NULL,
    ADD COLUMN ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER BOOLEAN NULL,
    ADD COLUMN JOBBER_BRUKER_AKTIVT_MED_VIRKSOMHET BOOLEAN NULL;