ALTER TABLE TILBAKEKREVINGSBEHANDLING
    ADD COLUMN VENTE_GRUNN VARCHAR(40);
ALTER TABLE TILBAKEKREVINGSBEHANDLING
    ADD COLUMN GJENOPPTAS DATE;

ALTER TABLE TILBAKEKREVINGSHENDELSE
    ADD COLUMN VENTE_GRUNN VARCHAR(40);
ALTER TABLE TILBAKEKREVINGSHENDELSE
    ADD COLUMN GJENOPPTAS DATE;
