ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN FASE TEXT NULL;

ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER BOOLEAN NULL;

ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
    ADD COLUMN JOBBER_BRUKER_AKTIVT_MED_VIRKSOMHET BOOLEAN NULL;

-- backfill: eksisterende oppstartsdata får fase OPPSTART
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING v
SET FASE = 'OPPSTART'
WHERE EXISTS (
    SELECT 1 FROM EGEN_VIRKSOMHET_OPPSTART_PERIODE p
    WHERE p.PERIODER_ID = v.EGEN_VIRKSOMHET_OPPSTART_PERIODER_ID
)
  AND v.FASE IS NULL;

-- backfill: eksisterende utviklingsdata får fase UTVIKLING
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING v
SET FASE = 'UTVIKLING'
WHERE EXISTS (
    SELECT 1 FROM EGEN_VIRKSOMHET_UTVIKLING_PERIODE p
    WHERE p.PERIODER_ID = v.EGEN_VIRKSOMHET_UTVIKLING_PERIODER_ID
)
  AND v.FASE IS NULL;

-- eksisterende oppstartsbedrifter skal settes til true
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING
SET ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER = TRUE
WHERE FASE = 'OPPSTART'
  AND ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER IS NULL;

-- utvikling skal være null
UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING
SET ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER = NULL
WHERE FASE = 'UTVIKLING'
  AND ER_REGISTRERT_I_NODVENDIGE_OFFENTLIGE_REGISTER IS NULL;

UPDATE ETABLERING_EGEN_VIRKSOMHET_VURDERING
SET JOBBER_BRUKER_AKTIVT_MED_VIRKSOMHET = TRUE
WHERE FASE IS NULL
  AND JOBBER_BRUKER_AKTIVT_MED_VIRKSOMHET IS NULL;

-- senere:
-- ALTER TABLE ETABLERING_EGEN_VIRKSOMHET_VURDERING
--     ALTER COLUMN FASE SET NOT NULL;