UPDATE MOTTATT_DOKUMENT
SET REFERANSE_TYPE = 'JOURNALPOST',
    REFERANSE = JOURNALPOST
WHERE REFERANSE IS NULL;

CREATE UNIQUE INDEX UIDX_MOTTATT_DOKUMENT_SAK_REFERANSE
    ON MOTTATT_DOKUMENT(SAK_ID, REFERANSE_TYPE, REFERANSE);