CREATE TABLE HELSEOPPHOLD_VURDERINGER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE HELSEOPPHOLD_VURDERING
(
    ID                          BIGSERIAL                              NOT NULL PRIMARY KEY,
    HELSEOPPHOLD_VURDERINGER_ID BIGINT                                 NOT NULL REFERENCES HELSEOPPHOLD_VURDERINGER (ID),
    KOST_OG_LOSJI               BOOLEAN                                NOT NULL,
    FORSORGER_EKTEFELLE         BOOLEAN NULL,
    FASTE_UTGIFTER              BOOLEAN NULL,
    BEGRUNNELSE                 TEXT                                   NOT NULL,
    PERIODE                     DATERANGE                              NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_HELSEOPPHOLD_VURDERINGER_VURDERING ON HELSEOPPHOLD_VURDERING (HELSEOPPHOLD_VURDERINGER_ID);

ALTER TABLE OPPHOLD_GRUNNLAG
    ADD COLUMN HELSEOPPHOLD_VURDERINGER_ID BIGINT references HELSEOPPHOLD_VURDERINGER (ID);
