ALTER TABLE STUDENT_VURDERING ALTER COLUMN AVBRUTT_DATO DROP NOT NULL;
ALTER TABLE STUDENT_VURDERING ALTER COLUMN godkjent_studie_av_laanekassen DROP NOT NULL;
ALTER TABLE STUDENT_VURDERING ALTER COLUMN avbrutt_pga_sykdom_eller_skade DROP NOT NULL;
ALTER TABLE STUDENT_VURDERING ALTER COLUMN har_behov_for_behandling DROP NOT NULL;
ALTER TABLE STUDENT_VURDERING ALTER COLUMN avbrudd_mer_enn_6_maaneder DROP NOT NULL;
