CREATE TABLE UNDERVEIS_SPORING
(
    ID                BIGSERIAL     NOT NULL PRIMARY KEY,
    FAKTAGRUNNLAG     text NULL,
    VERSJON           VARCHAR(100)  NOT NULL
);

ALTER TABLE UNDERVEIS_GRUNNLAG ADD COLUMN SPORING_ID BIGINT references UNDERVEIS_SPORING (ID);
