CREATE TABLE SYKDOM_VURDERING_BIDIAGNOSER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES SYKDOM_VURDERING (ID),
    KODE  VARCHAR(25) NOT NULL
);