-- Årsak til behandling

CREATE TABLE AARSAK_TIL_BEHANDLING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AARSAK        VARCHAR(150)                           NOT NULL,
    PERIODE       DATERANGE                              NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_AARSAK_TIL_BEHANDLING_TID ON AARSAK_TIL_BEHANDLING (BEHANDLING_ID, OPPRETTET_TID);
CREATE UNIQUE INDEX UIDX_AARSAK_TIL_BEHANDLING ON AARSAK_TIL_BEHANDLING (BEHANDLING_ID, AARSAK, PERIODE);
