ALTER TABLE BRUKER_PERSONOPPLYSNING
    ADD COLUMN LAND             varchar(50) NOT NULL DEFAULT 'XUK',
    ADD COLUMN GYLDIGFRAOGMED   DATE        NULL,
    ADD COLUMN GYLDIGTILOGMED   DATE        NULL,
    ADD COLUMN STATUS           varchar(50) NOT NULL DEFAULT 'inaktiv';