CREATE TABLE OPPGITT_UTENLANDSOPPHOLD(
     ID                                   BIGSERIAL   NOT NULL   PRIMARY KEY,
     BODD_I_NORGE_SISTE_FEM_AAR           BOOLEAN     NOT NULL,
     ARBEIDET_I_NORGE_SISTE_FEM_AAR       BOOLEAN     NOT NULL,
     ARBEIDET_UTENFOR_NORGE_FOR_SYKDOM    BOOLEAN     NOT NULL,
     I_TILLEGG_ARBEID_UTENFOR_NORGE       BOOLEAN     NOT NULL,
     OPPRETTET_TID                        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE UTENLANDS_PERIODE(
    ID                              BIGSERIAL       NOT NULL   PRIMARY KEY,
    LAND                            VARCHAR(50)     NULL,
    TIL_DATO                        DATE            NULL,
    FRA_DATO                        DATE            NULL,
    I_ARBEID                        BOOLEAN         NOT NULL,
    UTENLANDS_ID                    VARCHAR(50)     NULL,
    OPPGITT_UTENLANDSOPPHOLD_ID     BIGINT          NULL REFERENCES OPPGITT_UTENLANDSOPPHOLD (ID),
    OPPRETTET_TID                   TIMESTAMP(3)    DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_UTENLANDS_PERIODE_OPPGITT_UTENLANDSOPPHOLD_ID ON UTENLANDS_PERIODE (OPPGITT_UTENLANDSOPPHOLD_ID);

CREATE TABLE OPPGITT_UTENLANDSOPPHOLD_GRUNNLAG
(
    ID                              BIGSERIAL                              NOT NULL   PRIMARY KEY,
    BEHANDLING_ID                   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    JOURNALPOST_ID                  VARCHAR(50)                            NOT NULL,
    OPPGITT_UTENLANDSOPPHOLD_ID     BIGINT                                 NOT NULL REFERENCES OPPGITT_UTENLANDSOPPHOLD (ID),
    AKTIV                           BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID                   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_OPPGITT_UTENLANDSOPPHOLD_GRUNNLAG_BEHANDLING_ID ON OPPGITT_UTENLANDSOPPHOLD_GRUNNLAG (BEHANDLING_ID);