CREATE TABLE LOVVALG_MEDLEMSKAP_MANUELL_VURDERING(
    ID                          BIGSERIAL       NOT NULL   PRIMARY KEY,
    TEKSTVURDERING_LOVVALG      TEXT            NOT NULL,
    LOVVALGS_LAND               VARCHAR(3)      NULL,
    TEKSTVURDERING_MEDLEMSKAP   TEXT            NOT NULL,
    VAR_MEDLEM_I_FOLKETRYGDEN   BOOLEAN         NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG
    ADD COLUMN MANUELL_VURDERING_ID BIGINT NULL REFERENCES LOVVALG_MEDLEMSKAP_MANUELL_VURDERING (ID);

CREATE INDEX IDX_MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG_MANUELL_VURDERING_ID ON MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG (MANUELL_VURDERING_ID);