ALTER TABLE FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING
    DROP COLUMN OPPFYLLER_UNNTAKS_VILKÅR,
    ADD COLUMN VAR_MEDLEM_MED_NEDSATT_ARBEIDSEVNE BOOLEAN DEFAULT FALSE NOT NULL,
    ADD COLUMN MEDLEM_MED_UNNTAKT_AV_MAKS_FEM_AAR BOOLEAN DEFAULT FALSE NOT NULL;