CREATE TABLE PERSONOPPLYSNINGER_FORUTGAAENDE
(
    ID                          BIGSERIAL                                   NOT NULL PRIMARY KEY,
    OPPRETTET_TID               TIMESTAMP(3)      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PERSONOPPLYSNING_FORUTGAAENDE
(
    ID                               BIGSERIAL         NOT NULL PRIMARY KEY,
    PERSON_ID                        BIGINT            NOT NULL REFERENCES PERSON,
    FODSELSDATO                      DATE              NOT NULL,
    DODSDATO                         DATE              DEFAULT NULL,
    PERSONOPPLYSNINGER_ID            BIGINT            NOT NULL REFERENCES PERSONOPPLYSNINGER_FORUTGAAENDE (ID),
    OPPRETTET_TID                    TIMESTAMP(3)      DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_PERSONOPPLYSNING_FORUTGAAENDE ON PERSONOPPLYSNING_FORUTGAAENDE (PERSON_ID, PERSONOPPLYSNINGER_ID);


-- Aggerat
CREATE TABLE BRUKER_LAND_FORUTGAAENDE_AGGREGAT(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BRUKER_LAND_FORUTGAAENDE(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    LAND            VARCHAR(50)  DEFAULT 'XUK' NOT NULL,
    GYLDIGFRAOGMED  DATE NULL,
    GYLDIGTILOGMED  DATE NULL,
    LANDKODER_ID    BIGINT      NOT NULL REFERENCES BRUKER_LAND_FORUTGAAENDE_AGGREGAT(ID),
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_BRUKER_LAND_LANDKODER_ID ON BRUKER_LAND_FORUTGAAENDE (LANDKODER_ID);

-- Aggerat
CREATE TABLE BRUKER_STATUSER_FORUTGAAENDE_AGGREGAT(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BRUKER_STATUSER_FORUTGAAENDE(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    STATUS          VARCHAR(50)  DEFAULT 'inaktiv' NOT NULL,
    STATUSER_ID     BIGINT       NOT NULL REFERENCES BRUKER_STATUSER_FORUTGAAENDE_AGGREGAT(ID),
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_BRUKER_STATUSER_STATUSER_ID ON BRUKER_STATUSER_FORUTGAAENDE (STATUSER_ID);

CREATE TABLE BRUKER_PERSONOPPLYSNING_FORUTGAAENDE
(
    ID              BIGSERIAL    NOT NULL PRIMARY KEY,
    FODSELSDATO     DATE         NOT NULL,
    DODSDATO        DATE         DEFAULT NULL,
    LANDKODER_ID    BIGINT    NOT NULL REFERENCES BRUKER_LAND_FORUTGAAENDE_AGGREGAT(ID),
    STATUSER_ID     BIGINT    NOT NULL REFERENCES BRUKER_STATUSER_FORUTGAAENDE_AGGREGAT(ID) ,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_BRUKER_PERSONOPPLYSNING_LANDKODER_ID ON BRUKER_PERSONOPPLYSNING_FORUTGAAENDE (LANDKODER_ID);
CREATE INDEX IDX_BRUKER_PERSONOPPLYSNING_STATUSER_ID ON BRUKER_PERSONOPPLYSNING_FORUTGAAENDE (STATUSER_ID);


CREATE TABLE PERSONOPPLYSNING_FORUTGAAENDE_GRUNNLAG
(
    ID                         BIGSERIAL    NOT NULL PRIMARY KEY,
    BEHANDLING_ID              BIGINT       NOT NULL REFERENCES BEHANDLING,
    BRUKER_PERSONOPPLYSNING_ID BIGINT       NOT NULL REFERENCES BRUKER_PERSONOPPLYSNING_FORUTGAAENDE (ID),
    PERSONOPPLYSNINGER_ID      BIGINT       NULL REFERENCES PERSONOPPLYSNINGER_FORUTGAAENDE (ID),
    AKTIV                      BOOLEAN      DEFAULT TRUE NOT NULL,
    OPPRETTET_TID              TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IDX_PERSONOPPLYSNING_FORUTGAAENDE_BEHANDLING_ID ON PERSONOPPLYSNING_FORUTGAAENDE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);