UPDATE SYKDOM_VURDERING
    SET OPPRETTET_TID = CURRENT_TIMESTAMP
    WHERE OPPRETTET_TID IS NULL;

ALTER TABLE SYKDOM_VURDERING
    ADD COLUMN VURDERT_AV_IDENT TEXT NOT NULL DEFAULT '',
    ALTER COLUMN OPPRETTET_TID SET NOT NULL;