-- Aggregering
CREATE TABLE ARBEIDER_FORUTGAAENDE
(
    ID              BIGSERIAL                              NOT NULL   PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ARBEID_FORUTGAAENDE
(
    ID                      BIGSERIAL                              NOT NULL   PRIMARY KEY,
    IDENTIFIKATOR           VARCHAR(30)                            NOT NULL,
    ARBEIDSFORHOLD_KODE     VARCHAR(50)                            NOT NULL,
    ARBEIDER_ID             BIGINT                                 NOT NULL REFERENCES ARBEIDER_FORUTGAAENDE (ID),
    STARTDATO               DATE                                   NOT NULL,
    SLUTTDATO               DATE                                   NULL,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_ARBEID_FORUTGAAENDE_ARBEIDER_ID ON ARBEID_FORUTGAAENDE (ARBEIDER_ID);

-- Aggregering
CREATE TABLE INNTEKTER_I_NORGE_FORUTGAAENDE
(
    ID              BIGSERIAL                              NOT NULL   PRIMARY KEY,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE INNTEKT_I_NORGE_FORUTGAAENDE
(
    ID                          BIGSERIAL                              NOT NULL   PRIMARY KEY,
    IDENTIFIKATOR               VARCHAR(30)                            NOT NULL,
    BELOEP                      NUMERIC                                NOT NULL,
    SKATTEMESSIG_BOSATT_LAND    VARCHAR(3)                             NULL,
    OPPTJENINGS_LAND            VARCHAR(3)                             NULL,
    INNTEKT_TYPE                VARCHAR(50)                            NULL,
    PERIODE                     DATERANGE                              NOT NULL,
    INNTEKTER_I_NORGE_ID        BIGINT                                 NOT NULL REFERENCES INNTEKTER_I_NORGE_FORUTGAAENDE (ID),
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_INNTEKT_I_NORGE_FORUTGAAENDE_INNTEKTER_I_NORGE_ID ON INNTEKT_I_NORGE_FORUTGAAENDE (INNTEKTER_I_NORGE_ID);

CREATE TABLE FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING(
      ID                          BIGSERIAL       NOT NULL PRIMARY KEY,
      BEGRUNNELSE                 TEXT            NOT NULL,
      HAR_FORUTGAAENDE_MEDLEMSKAP BOOLEAN         NOT NULL,
      OPPFYLLER_UNNTAKS_VILKÅR    BOOLEAN DEFAULT FALSE NOT NULL ,
      OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE FORUTGAAENDE_MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG
(
    ID                              BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    MEDLEMSKAP_UNNTAK_PERSON_ID     BIGINT                                 NULL REFERENCES MEDLEMSKAP_FORUTGAAENDE_UNNTAK_PERSON (ID),
    INNTEKTER_I_NORGE_ID            BIGINT                                 NULL REFERENCES INNTEKT_I_NORGE_FORUTGAAENDE (ID),
    ARBEIDER_ID                     BIGINT                                 NULL REFERENCES ARBEIDER_FORUTGAAENDE (ID),
    MANUELL_VURDERING_ID            BIGINT                                 NULL REFERENCES FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING (ID);
    AKTIV                           BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID                   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_FORUTGAAENDE_MEDLEMSKAP_GRUNNLAG_BEHANDLING_ID ON FORUTGAAENDE_MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG (BEHANDLING_ID);
CREATE INDEX IDX_FORUTGAAENDE_MEDLEMSKAP_MANUELL_VURDERING_ID ON FORUTGAAENDE_MEDLEMSKAP_ARBEID_OG_INNTEKT_I_NORGE_GRUNNLAG (MANUELL_VURDERING_ID);

