CREATE TABLE MELDEPERIODE_GRUNNLAG(
    ID BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT NOT NULL REFERENCES BEHANDLING(ID),
    OPPRETTET TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AKTIV BOOLEAN NOT NULL
);

CREATE TABLE MELDEPERIODE(
    ID BIGSERIAL PRIMARY KEY,
    MELDEPERIODEGRUNNLAG_ID BIGINT NOT NULL REFERENCES MELDEPERIODE_GRUNNLAG(ID),
    OPPRETTET TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PERIODE daterange NOT NULL
);

CREATE INDEX BEHANDLING_ID_IDX ON MELDEPERIODE_GRUNNLAG(BEHANDLING_ID) WHERE AKTIV = TRUE;
CREATE INDEX MELDEPERIODER_BEHANDLING_ID_IDX ON MELDEPERIODE(MELDEPERIODEGRUNNLAG_ID)