ALTER TABLE LOVVALG_MEDLEMSKAP_MANUELL_VURDERING
    ADD COLUMN vurdert_av varchar(50) NOT NULL DEFAULT 'Ukjent';

ALTER TABLE LOVVALG_MEDLEMSKAP_MANUELL_VURDERING
    ALTER COLUMN vurdert_av DROP DEFAULT;