CREATE TABLE VEDTAK
(
    ID               BIGSERIAL    NOT NULL PRIMARY KEY,
    BEHANDLING_ID    BIGINT       NOT NULL REFERENCES BEHANDLING (ID),
    VEDTAKSTIDSPUNKT TIMESTAMP(3) NOT NULL
);

CREATE UNIQUE INDEX UIDX_VEDTAK_BEHANDLING_ID ON VEDTAK (BEHANDLING_ID);
