package no.nav.aap.behandlingsflyt.repository.sak

import java.io.PrintWriter
import java.sql.Array
import java.sql.Blob
import java.sql.CallableStatement
import java.sql.Clob
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.NClob
import java.sql.PreparedStatement
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Savepoint
import java.sql.Statement
import java.sql.Struct
import java.util.Properties
import java.util.concurrent.Executor
import java.util.concurrent.atomic.AtomicInteger
import java.util.logging.Logger
import javax.sql.DataSource

/**
 * Wrapper rundt DataSource som teller antall prepareStatement-kall.
 * Brukes til å bevise at cachen reduserer antall SQL-queries.
 *
 * Eksempel:
 *   val countingDs = CountingDataSource(realDataSource)
 *   countingDs.transaction { conn -> repo.hent(id); repo.hent(id) }
 *   assertThat(countingDs.queryCount).isEqualTo(forventetAntall)
 */
class CountingDataSource(private val delegate: DataSource) : DataSource {
    private val _queryCount = AtomicInteger(0)

    val queryCount: Int get() = _queryCount.get()
    fun reset() = _queryCount.set(0)

    override fun getConnection(): Connection = CountingConnection(delegate.connection, _queryCount)
    override fun getConnection(username: String, password: String): Connection =
        CountingConnection(delegate.getConnection(username, password), _queryCount)

    override fun getLogWriter(): PrintWriter = delegate.logWriter
    override fun setLogWriter(out: PrintWriter) { delegate.logWriter = out }
    override fun setLoginTimeout(seconds: Int) { delegate.loginTimeout = seconds }
    override fun getLoginTimeout(): Int = delegate.loginTimeout
    override fun getParentLogger(): Logger = delegate.parentLogger
    override fun <T : Any> unwrap(iface: Class<T>): T = delegate.unwrap(iface)
    override fun isWrapperFor(iface: Class<*>): Boolean = delegate.isWrapperFor(iface)
}

/**
 * Wrapper rundt Connection som teller prepareStatement-kall.
 * Delegerer alt annet til den underliggende Connection.
 */
private class CountingConnection(
    private val delegate: Connection,
    private val counter: AtomicInteger,
) : Connection {
    override fun prepareStatement(sql: String): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql)
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql, autoGeneratedKeys)
    }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql, columnIndexes)
    }

    override fun prepareStatement(sql: String, columnNames: kotlin.Array<String>): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql, columnNames)
    }

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql, resultSetType, resultSetConcurrency)
    }

    override fun prepareStatement(
        sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int
    ): PreparedStatement {
        counter.incrementAndGet()
        return delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
    }

    // Resten delegeres til den underliggende Connection
    override fun close() = delegate.close()
    override fun isClosed(): Boolean = delegate.isClosed
    override fun commit() = delegate.commit()
    override fun rollback() = delegate.rollback()
    override fun rollback(savepoint: Savepoint?) = delegate.rollback(savepoint)
    override fun setAutoCommit(autoCommit: Boolean) { delegate.autoCommit = autoCommit }
    override fun getAutoCommit(): Boolean = delegate.autoCommit
    override fun isReadOnly(): Boolean = delegate.isReadOnly
    override fun setReadOnly(readOnly: Boolean) { delegate.isReadOnly = readOnly }
    override fun getTransactionIsolation(): Int = delegate.transactionIsolation
    override fun setTransactionIsolation(level: Int) { delegate.transactionIsolation = level }
    override fun getWarnings(): SQLWarning? = delegate.warnings
    override fun clearWarnings() = delegate.clearWarnings()
    override fun getMetaData(): DatabaseMetaData = delegate.metaData
    override fun getCatalog(): String? = delegate.catalog
    override fun setCatalog(catalog: String?) { delegate.catalog = catalog }
    override fun getSchema(): String? = delegate.schema
    override fun setSchema(schema: String?) { delegate.schema = schema }
    override fun getHoldability(): Int = delegate.holdability
    override fun setHoldability(holdability: Int) { delegate.holdability = holdability }
    override fun getClientInfo(): Properties = delegate.clientInfo
    override fun getClientInfo(name: String?): String? = delegate.getClientInfo(name)
    override fun setClientInfo(name: String?, value: String?) = delegate.setClientInfo(name, value)
    override fun setClientInfo(properties: Properties?) = delegate.setClientInfo(properties)
    override fun getNetworkTimeout(): Int = delegate.networkTimeout
    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) = delegate.setNetworkTimeout(executor, milliseconds)
    override fun abort(executor: Executor?) = delegate.abort(executor)
    override fun setSavepoint(): Savepoint = delegate.setSavepoint()
    override fun setSavepoint(name: String?): Savepoint = delegate.setSavepoint(name)
    override fun releaseSavepoint(savepoint: Savepoint?) = delegate.releaseSavepoint(savepoint)
    override fun createStatement(): Statement = delegate.createStatement()
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
        delegate.createStatement(resultSetType, resultSetConcurrency)
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement =
        delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability)
    override fun prepareCall(sql: String?): CallableStatement = delegate.prepareCall(sql)
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int): CallableStatement =
        delegate.prepareCall(sql, resultSetType, resultSetConcurrency)
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement =
        delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
    override fun nativeSQL(sql: String?): String = delegate.nativeSQL(sql)
    override fun createClob(): Clob = delegate.createClob()
    override fun createBlob(): Blob = delegate.createBlob()
    override fun createNClob(): NClob = delegate.createNClob()
    override fun createSQLXML(): SQLXML = delegate.createSQLXML()
    override fun createArrayOf(typeName: String?, elements: kotlin.Array<out Any>?): Array = delegate.createArrayOf(typeName, elements)
    override fun createStruct(typeName: String?, attributes: kotlin.Array<out Any>?): Struct = delegate.createStruct(typeName, attributes)
    override fun isValid(timeout: Int): Boolean = delegate.isValid(timeout)
    override fun <T : Any> unwrap(iface: Class<T>): T = delegate.unwrap(iface)
    override fun isWrapperFor(iface: Class<*>): Boolean = delegate.isWrapperFor(iface)
    override fun getTypeMap(): MutableMap<String, Class<*>> = delegate.typeMap
    override fun setTypeMap(map: MutableMap<String, Class<*>>?) { delegate.typeMap = map }
    override fun beginRequest() = delegate.beginRequest()
    override fun endRequest() = delegate.endRequest()
    override fun setShardingKeyIfValid(shardingKey: java.sql.ShardingKey?, timeout: Int): Boolean =
        delegate.setShardingKeyIfValid(shardingKey, timeout)
    override fun setShardingKeyIfValid(shardingKey: java.sql.ShardingKey?, superShardingKey: java.sql.ShardingKey?, timeout: Int): Boolean =
        delegate.setShardingKeyIfValid(shardingKey, superShardingKey, timeout)
    override fun setShardingKey(shardingKey: java.sql.ShardingKey?) = delegate.setShardingKey(shardingKey)
    override fun setShardingKey(shardingKey: java.sql.ShardingKey?, superShardingKey: java.sql.ShardingKey?) =
        delegate.setShardingKey(shardingKey, superShardingKey)
}
