package no.nav.aap.behandlingsflyt.sakogbehandling.flyt

enum class VurderingType {
    FØRSTEGANGSBEHANDLING,
    REVURDERING,
    MELDEKORT,
    UTVID_VEDTAKSLENGDE,
    MIGRER_RETTIGHETSPERIODE,
    AUTOMATISK_BREV,
    EFFEKTUER_AKTIVITETSPLIKT,
    EFFEKTUER_AKTIVITETSPLIKT_11_9,
    IKKE_RELEVANT
}
