package no.nav.aap.behandlingsflyt.kontrakt.hendelse

public enum class InnsendingType {
    SØKNAD,

    /**
     * Dette er egentlig en dokument-type, ikke en egen innsending, da denne
     * typen opprettes i Kelvin.
     */
    AKTIVITETSKORT,
    MELDEKORT,
    LEGEERKLÆRING,
    LEGEERKLÆRING_AVVIST,
    DIALOGMELDING,
    KLAGE,
    ANNET_RELEVANT_DOKUMENT,
    MANUELL_REVURDERING,
    OMGJØRING_KLAGE_REVURDERING,
    ARBEIDSUTPRØVING,
    BARNETILLEGG,
    ETABLERING,
    FENGSEL_VARETEKT,
    LÆRLING,
    MEDLEMSKAP,
    PARTSINNSYN,
    REFUSJONSKRAV,
    SLUTTAVTALE,
    STUDENTBESTEMMELSEN,
    YRKESSKADE,
    KARAKTERUTSKRIFTER_CV,
    HELSEOPPLYSNINGER,
    ETTERSENDELSE_TIL_KLAGE,
    ETTERSENDELSE_TIL_FEILUTBETALING,
    TILTAKSRAPPORT,

    /**
     * Legger til ny årsak på en behandling, men oppretter ikke ny behandling.
     */
    NY_ÅRSAK_TIL_BEHANDLING,
    KABAL_HENDELSE,
    TILBAKEKREVING_HENDELSE,
    FAGSYSTEMINFO_BEHOV_HENDELSE,
    PDL_HENDELSE_DODSFALL_BRUKER,
    PDL_HENDELSE_DODSFALL_BARN,
    PDL_HENDELSE_FOLKEREGISTERIDENT,
    OPPFØLGINGSOPPGAVE,
    INSTITUSJONSOPPHOLD,
    SYKEPENGE_VEDTAK_HENDELSE,
    FORELDREPENGE_VEDTAK_HENDELSE,
    UFØRE_VEDTAK_HENDELSE
}