ALTER TABLE BARN_VURDERING
    DROP CONSTRAINT BARN_VURDERING_BARN_VURDERING_PERIODE_ID_FKEY,
    DROP COLUMN BARN_VURDERING_PERIODE_ID,
    ADD COLUMN BEGRUNNELSE                TEXT        NOT NULL,
    ADD COLUMN SKAL_BEREGNES_BARNETILLEGG BOOLEAN     NOT NULL,
    ADD COLUMN PERIODER_ID BIGINT REFERENCES BARN_VURDERING_PERIODER(ID) NOT NULL;

ALTER TABLE  BARN_VURDERING_PERIODE
    DROP CONSTRAINT BARN_VURDERING_PERIODE_PERIODER_ID_FKEY,
    DROP COLUMN PERIODER_ID,
    ADD COLUMN VURDERING_ID BIGINT REFERENCES BARN_VURDERING(ID) NOT NULL;


