

CREATE TABLE SONINGSFORHOLD_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES SONINGSFORHOLD_GRUNNLAG (ID),
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_SONINGSFORHOLD_VURDERING_DOKUMENTER ON SONINGSFORHOLD_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE HELSEINSTITUSJON_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES HELSEINSTITUSJON_GRUNNLAG (ID),
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_HELSEINSTITUSJON_VURDERING_DOKUMENTER ON HELSEINSTITUSJON_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

ALTER TABLE SONINGSFORHOLD_GRUNNLAG RENAME TO SONINGSFORHOLD_VURDERING;
ALTER TABLE HELSEINSTITUSJON_GRUNNLAG RENAME TO HELSEINSTITUSJON_VURDERING;
