ALTER TABLE MELDEPLIKT_FRITAK_GRUNNLAG ADD COLUMN BEGRUNNELSE TEXT NOT NULL DEFAULT '';
ALTER TABLE MELDEPLIKT_FRITAK_GRUNNLAG ALTER COLUMN BEGRUNNELSE DROP DEFAULT;

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING DROP COLUMN BEGRUNNELSE;