ALTER TABLE SYKDOM_VURDERING
    ADD COLUMN HAR_SYKDOM_SKADE_LYTE BOOLEAN NOT NULL DEFAULT TRUE,
    ALTER COLUMN ER_ARBEIDSEVNE_NEDSATT DROP NOT NULL;

ALTER TABLE SYKDOM VURDERING ALTER COLUMN DEFAULT