DROP TABLE BARN_VURDERING_GRUNNLAG;
DROP TABLE barn_vurdering;
DROP TABLE BARN_VURDERING_PERIODE;
DROP TABLE BARN_VURDERING_PERIODER;


CREATE TABLE BARN_VURDERINGER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BARN_VURDERING
(
    ID                  BIGSERIAL                              NOT NULL PRIMARY KEY,
    IDENT               VARCHAR(19)                            NOT NULL,
    BARN_VURDERINGER_ID BIGINT                                 NOT NULL REFERENCES BARN_VURDERINGER (ID),
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BARN_VURDERING_IDENT ON BARN_VURDERING (BARN_VURDERINGER_ID, IDENT);


CREATE TABLE BARN_VURDERING_PERIODE
(
    ID                 BIGSERIAL                              NOT NULL PRIMARY KEY,
    BARN_VURDERING_ID  BIGINT                                 NOT NULL REFERENCES BARN_VURDERING (ID),
    PERIODE            DATERANGE                              NOT NULL,
    BEGRUNNELSE        TEXT                                   NOT NULL,
    HAR_FORELDREANSVAR BOOLEAN                                NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BARN_VURDERING_PERIODE
    ADD CONSTRAINT BARN_VURDERING_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        BARN_VURDERING_ID WITH =,
        PERIODE WITH &&
        );

ALTER TABLE BARNOPPLYSNING_GRUNNLAG
    ADD COLUMN vurderte_barn_id BIGINT references BARN_VURDERINGER;