
ALTER TABLE BISTAND
    ADD COLUMN BEHOV_FOR_AKTIV_BEHANDLING BOOLEAN NOT NULL DEFAULT false, ADD COLUMN BEHOV_FOR_ARBEIDSRETTET_TILTAK BOOLEAN NOT NULL DEFAULT false, ADD COLUMN BEHOV_FOR_ANNEN_OPPFOELGING BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE BISTAND ALTER COLUMN BEHOV_FOR_AKTIV_BEHANDLING DROP DEFAULT;
ALTER TABLE BISTAND ALTER COLUMN BEHOV_FOR_ARBEIDSRETTET_TILTAK DROP DEFAULT;
ALTER TABLE BISTAND ALTER COLUMN BEHOV_FOR_ANNEN_OPPFOELGING DROP DEFAULT;
