CREATE TABLE MELDEPLIKT_FRITAK_PERIODE
(
    ID            BIGSERIAL NOT NULL PRIMARY KEY,
    VURDERING_ID  BIGINT    NOT NULL REFERENCES MELDEPLIKT_FRITAK_VURDERING (ID),
    PERIODE       DATERANGE NOT NULL,
    HAR_FRITAK    BOOLEAN   NOT NULL,
    CONSTRAINT    EXCLUDE_OVERLAPPING_PERIODE EXCLUDE USING GIST (PERIODE WITH &&)
);

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING ADD COLUMN BEGRUNNELSE TEXT NOT NULL DEFAULT '';
ALTER TABLE MELDEPLIKT_FRITAK_VURDERING ALTER COLUMN BEGRUNNELSE DROP DEFAULT;

ALTER TABLE MELDEPLIKT_FRITAK_GRUNNLAG DROP COLUMN BEGRUNNELSE;