-- Samordning
CREATE TABLE SAMORDNING_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE SAMORDNING_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES SAMORDNING_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    GRADERING     SMALLINT                               NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SAMORDNING_PERIODE
    ADD CONSTRAINT SAMORDNING_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
    );
CREATE TABLE SAMORDNING_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES SAMORDNING_PERIODER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_SAMORDNING_GRUNNLAG_BEHANDLING_ID ON SAMORDNING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);


-- Foreldrepenger
CREATE TABLE FORELDREPENGER_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES FORELDREPENGER_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    GRADERING     SMALLINT                               NULL,
    YTELSE        VARCHAR(50)                            NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE FORELDREPENGER_PERIODE
    ADD CONSTRAINT FORELDREPENGER_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
    );
CREATE TABLE FORELDREPENGER_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE FORELDREPENGER_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES FORELDREPENGER_PERIODER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_FORELDREPENGER_GRUNNLAG_BEHANDLING_ID ON FORELDREPENGER_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);


-- Sykepenger
CREATE TABLE SYKEPENGER_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES SYKEPENGER_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    GRADERING     SMALLINT                               NULL,
    KRONESUM      NUMERIC(21, 0)                         NULL,
    YTELSE        VARCHAR(50)                            NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SYKEPENGER_PERIODE
    ADD CONSTRAINT SYKEPENGER_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
    );
CREATE TABLE SYKEPENGER_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE SYKEPENGER_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES SYKEPENGER_PERIODER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SYKEPENGER_GRADERING_VURDERING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES SYKEPENGER_PERIODE (ID),
    GRADERING     SMALLINT                               NULL,
    BEGRUNNELSE   VARCHAR(50)                            NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_SYKEPENGER_GRUNNLAG_BEHANDLING_ID ON SYKEPENGER_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);