-- ARBEIDSEVNE GRUNNLAG

CREATE TABLE ARBEIDSEVNE
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ANDEL_AV_NEDSETTELSE SMALLINT                               NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ARBEIDSEVNE_GRUNNLAG
(
    ID             BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    ARBEIDSEVNE_ID BIGINT                                 NOT NULL REFERENCES ARBEIDSEVNE (ID),
    AKTIV          BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_ARBEIDSEVNE_GRUNNLAG_BEHANDLING_ID ON ARBEIDSEVNE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- BISTAND

CREATE TABLE BISTAND
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ER_BEHOV_FOR_BISTAND BOOLEAN                                NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BISTAND_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    BISTAND_ID    BIGINT                                 NOT NULL REFERENCES BISTAND (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_BISTAND_GRUNNLAG_BEHANDLING_ID ON BISTAND_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- FRITAK MELDEPLIKT

CREATE TABLE MELDEPLIKT_FRITAK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE MELDEPLIKT_FRITAK_VURDERING
(
    ID            BIGSERIAL NOT NULL PRIMARY KEY,
    MELDEPLIKT_ID BIGINT    NOT NULL REFERENCES MELDEPLIKT_FRITAK (ID),
    PERIODE       DATERANGE NOT NULL,
    BEGRUNNELSE   TEXT      NOT NULL,
    HAR_FRITAK    BOOLEAN   NOT NULL
);

CREATE INDEX IDX_MELDEPLIKT_FRITAK_VURDERING_MELDEPLIKT_ID ON MELDEPLIKT_FRITAK_VURDERING (MELDEPLIKT_ID);

CREATE TABLE MELDEPLIKT_FRITAK_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    MELDEPLIKT_ID BIGINT                                 NOT NULL REFERENCES MELDEPLIKT_FRITAK (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_MELDEPLIKT_FRITAK_GRUNNLAG_BEHANDLING_ID ON MELDEPLIKT_FRITAK_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- STUDENT

CREATE TABLE STUDENT_VURDERING
(
    ID           BIGSERIAL NOT NULL PRIMARY KEY,
    BEGRUNNELSE  TEXT      NULL,
    OPPFYLT      BOOLEAN   NOT NULL,
    AVBRUTT_DATO DATE      NULL
);

CREATE TABLE STUDENT_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES STUDENT_VURDERING,
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_STUDENT_VURDERING_DOKUMENTER ON STUDENT_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE STUDENT_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    STUDENT_ID    BIGINT                                 NULL REFERENCES STUDENT_VURDERING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_STUDENT_GRUNNLAG_HISTORIKK ON STUDENT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- SYKDOM

CREATE TABLE SYKDOM_VURDERING
(
    ID                                     BIGSERIAL   NOT NULL PRIMARY KEY,
    BEGRUNNELSE                            TEXT        NOT NULL,
    ER_SYKDOM_SKADE_LYTE_VESETLING_DEL     BOOLEAN     NOT NULL,
    ER_NEDSETTELSE_HOYERE_ENN_NEDRE_GRENSE BOOLEAN     NULL,
    NEDRE_GRENSE                           VARCHAR(25) NOT NULL,
    NEDSATT_ARBEIDSEVNE_DATO               DATE        NULL,
    YTTERLIGERE_NEDSATT_ARBEIDSEVNE_DATO   DATE        NULL
);

CREATE TABLE SYKDOM_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES SYKDOM_VURDERING (ID),
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_SYKDOM_VURDERING_DOKUMENTER ON SYKDOM_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE YRKESSKADE_VURDERING
(
    ID                   BIGSERIAL      NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT           NULL,
    ARSAKSSAMMENHENG     BOOLEAN        NOT NULL,
    SKADEDATO            DATE           NULL,
    ANDEL_AV_NEDSETTELSE SMALLINT       NULL,
    ANTATT_ARLIG_INNTEKT NUMERIC(19, 2) NULL
);
CREATE TABLE YRKESSKADE_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES YRKESSKADE_VURDERING (ID),
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_YRKESSKADE_VURDERING_DOKUMENTER ON YRKESSKADE_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE SYKDOM_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    YRKESSKADE_ID BIGINT                                 NULL REFERENCES YRKESSKADE_VURDERING (ID),
    SYKDOM_ID     BIGINT                                 NULL REFERENCES SYKDOM_VURDERING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_SYKDOM_GRUNNLAG_HISTORIKK ON SYKDOM_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- SYKEPENGEERSTATNING

CREATE TABLE SYKEPENGE_VURDERING
(
    ID          SERIAL  NOT NULL PRIMARY KEY,
    BEGRUNNELSE TEXT    NULL,
    OPPFYLT     BOOLEAN NOT NULL
);

CREATE TABLE SYKEPENGE_VURDERING_DOKUMENTER
(
    ID           SERIAL      NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES SYKEPENGE_VURDERING,
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_SYKEPENGE_VURDERING_DOKUMENTER ON SYKEPENGE_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE SYKEPENGE_ERSTATNING_GRUNNLAG
(
    ID            SERIAL                                 NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VURDERING_ID  BIGINT                                 NULL REFERENCES SYKEPENGE_VURDERING,
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_SYKEPENGE_VURDERING_GRUNNLAG_HISTORIKK ON SYKEPENGE_ERSTATNING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
