-- Samordning slutt-tabell
CREATE TABLE SAMORDNING_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE SAMORDNING_PERIODE
(
    ID                                      BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID                             BIGINT                                 NOT NULL REFERENCES SAMORDNING_PERIODER (ID),
    PERIODE                                 DATERANGE                              NOT NULL,
    GRADERING                               SMALLINT                               NOT NULL,
    OPPRETTET_TID                           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SAMORDNING_PERIODE
    ADD CONSTRAINT SAMORDNING_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
    );
CREATE TABLE SAMORDNING_GRUNNLAG
(
    ID                                      BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                           BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID                             BIGINT                                 NOT NULL REFERENCES SAMORDNING_PERIODER (ID),
    AKTIV                                   BOOLEAN DEFAULT TRUE                   NOT NULL,
    OPPRETTET_TID TIMESTAMP(3)              DEFAULT CURRENT_TIMESTAMP              NOT NULL
);
CREATE INDEX UIDX_SAMORDNING_GRUNNLAG_BEHANDLING_ID ON SAMORDNING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- Samordning-vurderinger
CREATE TABLE SAMORDNING_VURDERINGER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SAMORDNING_VURDERING
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    VURDERINGER_ID  BIGINT                                 NOT NULL REFERENCES SAMORDNING_VURDERINGER (ID),
    YTELSE_TYPE     VARCHAR(50)                            NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SAMORDNING_VURDERING_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODE       DATERANGE                              NOT NULL,
    VURDERING_ID  BIGINT                                 NOT NULL REFERENCES SAMORDNING_VURDERING (ID),
    GRADERING     SMALLINT                               NULL,
    KRONESUM      NUMERIC(21, 0)                         NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE SAMORDNING_VURDERING_PERIODE
    ADD CONSTRAINT SAMORDNING_VURDERING_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        VURDERING_ID WITH =,
        PERIODE WITH &&
    );
CREATE INDEX UIDX_SAMORDNING_VURDERING_VURDERINGER_ID ON SAMORDNING_VURDERING (VURDERINGER_ID);


-- Samordning-ytelser
CREATE TABLE SAMORDNING_YTELSER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SAMORDNING_YTELSE
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    YTELSE_TYPE     VARCHAR(50)                            NOT NULL,
    YTELSER_ID      BIGINT                                 NOT NULL REFERENCES SAMORDNING_YTELSER (ID),
    KILDE           VARCHAR(30)                            NOT NULL,
    SAKS_REF        VARCHAR(40)                            NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SAMORDNING_YTELSE_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    YTELSE_ID     BIGINT                                 NOT NULL REFERENCES SAMORDNING_YTELSE (ID),
    PERIODE       DATERANGE                              NOT NULL,
    GRADERING     SMALLINT                               NULL,
    KRONESUM      NUMERIC(21, 0)                         NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE SAMORDNING_YTELSE_PERIODE
    ADD CONSTRAINT SAMORDNING_YTELSE_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        YTELSE_ID WITH =,
        PERIODE WITH &&
    );
CREATE INDEX UIDX_SAMORDNING_YTELSE_YTELSER_ID ON SAMORDNING_YTELSE (YTELSER_ID);

-- Aggregering
CREATE TABLE SAMORDNING_YTELSEVURDERING_GRUNNLAG
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    YTELSER_ID      BIGINT                                 NOT NULL REFERENCES SAMORDNING_YTELSER (ID),
    VURDERINGER_ID  BIGINT                                 NULL REFERENCES SAMORDNING_VURDERINGER (ID),
    AKTIV           BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX UIDX_SAMORDNING_YTELSEVURDERING_GRUNNLAG_BEHANDLING_ID ON SAMORDNING_YTELSEVURDERING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);