DROP TABLE MELDEPLIKT_FRITAK_PERIODE;

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING
    ADD COLUMN HAR_FRITAK BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN OPPRINNELIG_FRA_DATO DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN GJELDENDE_PERIODE DATERANGE NOT NULL DEFAULT 'empty';

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING
    ALTER COLUMN HAR_FRITAK DROP DEFAULT,
    ALTER COLUMN GJELDENDE_PERIODE DROP DEFAULT,
    ALTER COLUMN OPPRINNELIG_FRA_DATO DROP DEFAULT;