CREATE TABLE AKTIVITETSKORT_GRUNNLAG
(
    ID                      BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID           BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AKTIVITETSKORTENE_ID    BIGINT                                 NOT NULL REFERENCES AKTIVITETSKORTENE (ID),
    AKTIV                   BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_AKTIVITETSKORT_GRUNNLAG_BEHANDLING_ID ON AKTIVITETSKORT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE AKTIVITETSKORTENE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE AKTIVITETSKORT
(
    ID                      BIGSERIAL                              NOT NULL PRIMARY KEY,
    AKTIVITETSKORTENE_ID    BIGINT                                 NOT NULL REFERENCES AKTIVITETSKORTENE (ID),
    JOURNALPOST             UUID                                   NOT NULL REFERENCES ,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_AKTIVITETSKORT ON AKTIVITETSKORT (JOURNALPOST);