DROP TABLE MELDEPLIKT_FRITAK_PERIODE;

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING
    ADD COLUMN HAR_FRITAK BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN FRA_DATO DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE MELDEPLIKT_FRITAK_VURDERING
    ALTER COLUMN HAR_FRITAK DROP DEFAULT,
    ALTER COLUMN FRA_DATO DROP DEFAULT;