DROP TABLE BRUDD_AKTIVITETSPLIKT;
CREATE TABLE BRUDD_AKTIVITETSPLIKT
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    SAK_ID        BIGINT                                 NOT NULL REFERENCES SAK (ID),
    NAV_IDENT     TEXT                                   NOT NULL,
    BRUDD         VARCHAR(60)                            NOT NULL,
    PERIODE       DATERANGE                              NOT NULL,
    BEGRUNNELSE   TEXT                                   NOT NULL,
    PARAGRAF      VARCHAR(20)                            NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    HENDELSE_ID   UUID                                   NOT NULL,
    INNSENDING_ID UUID                                   NOT NULL
);

ALTER TABLE MOTTATT_DOKUMENT ALTER COLUMN JOURNALPOST TYPE VARCHAR(38);

CREATE TABLE BRUDD_AKTIVITETSPLIKT_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BRUDD_AKTIVITETSPLIKT_GRUNNLAG_BEHANDLING_ID ON BRUDD_AKTIVITETSPLIKT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE BRUDD_AKTIVITETSPLIKTER
(
    ID                                BIGSERIAL NOT NULL PRIMARY KEY,
    BRUDD_AKTIVITETSPLIKT_GRUNNLAG_ID BIGINT    NOT NULL REFERENCES BRUDD_AKTIVITETSPLIKT_GRUNNLAG (ID),
    BRUDD_AKTIVITETSPLIKT_ID          BIGINT    NOT NULL REFERENCES BRUDD_AKTIVITETSPLIKT (ID)
);