CREATE TABLE BREVBESTILLING
(
    ID              BIGSERIAL       NOT NULL PRIMARY KEY,
    BEHANDLING_ID   BIGINT          NOT NULL                REFERENCES BEHANDLING (ID),
    TYPE_BREV       VARCHAR(100)    NOT NULL,
    REFERANSE       UUID UNIQUE     NOT NULL,
    STATUS          VARCHAR(100)    NOT NULL
);

CREATE INDEX IDX_BREVBESTILLING_REFERANSE ON BREVBESTILLING (REFERANSE);
CREATE UNIQUE INDEX UIDX_BREVBESTILLING_BEHANDLING_ID_TYPE_BREV ON BREVBESTILLING (BEHANDLING_ID, TYPE_BREV);