-- BEREGNINGSGRUNNLAG

CREATE TABLE BEREGNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNING_UFORE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_ID  BIGINT                                 NOT NULL REFERENCES BEREGNING (ID),
    TYPE          TEXT                                   NOT NULL,
    GJELDENDE     BOOLEAN                                NOT NULL,
    G_UNIT        NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BEREGNING_UFORE_BEHANDLING_ID ON BEREGNING_UFORE (BEREGNING_ID) WHERE (GJELDENDE = TRUE);
CREATE UNIQUE INDEX UIDX_BEREGNING_UFORE_TYPE ON BEREGNING_UFORE (BEREGNING_ID, TYPE);

CREATE TABLE BEREGNING_HOVED
(
    ID                 BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_UFORE_ID BIGINT                                 NOT NULL REFERENCES BEREGNING_UFORE (ID),
    G_UNIT             NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNING_YRKESSKADE
(
    ID                 BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_HOVED_ID BIGINT                                 NOT NULL REFERENCES BEREGNING_HOVED (ID),
    G_UNIT             NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNINGSGRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    BEREGNING_ID  BIGINT                                 NOT NULL REFERENCES BEREGNING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BEREGNINGSGRUNNLAG_BEHANDLING_ID ON BEREGNINGSGRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
