ALTER TABLE BEREGNING_UFORE_INNTEKT
    ADD COLUMN inntekt_justert_ufore_g NUMERIC(21, 10) NOT NULL DEFAULT 0,
    ADD COLUMN GRUNNBELOP NUMERIC(19, 2) NOT NULL DEFAULT 0,
    ADD COLUMN INNTEKT_I_G NUMERIC(21, 10) NOT NULL DEFAULT 0;


ALTER TABLE BEREGNING_UFORE_INNTEKT
    ALTER COLUMN inntekt_justert_ufore_g DROP DEFAULT,
    ALTER COLUMN GRUNNBELOP DROP DEFAULT,
    ALTER COLUMN INNTEKT_I_G DROP DEFAULT;