CREATE TABLE ARBEIDSEVNE_VURDERING
(
    ID                BIGSERIAL                              NOT NULL PRIMARY KEY,
    ARBEIDSEVNE_ID    BIGINT                                 NOT NULL REFERENCES ARBEIDSEVNE (ID),
    FRA_DATO          DATE                                   NOT NULL,
    BEGRUNNELSE       TEXT                                   NOT NULL,
    ANDEL_ARBEIDSEVNE SMALLINT                               NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_ARBEIDSEVNE_VURDERING_ARBEIDSEVNE_ID ON ARBEIDSEVNE_VURDERING (ARBEIDSEVNE_ID);

ALTER TABLE ARBEIDSEVNE
    DROP COLUMN BEGRUNNELSE,
    DROP COLUMN ANDEL_AV_NEDSETTELSE;