CREATE TABLE ARBEIDSEVNE_VURDERING
(
    ID                   BIGSERIAL    NOT NULL PRIMARY KEY,
    ARBEIDSEVNE_ID       BIGINT       NOT NULL REFERENCES ARBEIDSEVNE (ID),
    FRA_DATO             DATE         NOT NULL,
    BEGRUNNELSE          TEXT         NOT NULL,
    ANDEL_AV_NEDSETTELSE SMALLINT     NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) NOT NULL
);

ALTER TABLE ARBEIDSEVNE
    DROP COLUMN BEGRUNNELSE,
    DROP COLUMN ANDEL_AV_NEDSETTELSE;