CREATE TABLE SONING_VURDERINGER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SONING_VURDERING
(
    ID                    BIGSERIAL                              NOT NULL PRIMARY KEY,
    SONING_VURDERINGER_ID BIGINT                                 NOT NULL REFERENCES SONING_VURDERINGER (ID),
    SKAL_OPPHORE          BOOLEAN                                NOT NULL,
    BEGRUNNELSE           TEXT                                   NOT NULL,
    FRA_DATO              DATE                                   NOT NULL,
    OPPRETTET_TID         TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_SONING_VURDERING_VURDERINGER ON SONING_VURDERING (SONING_VURDERINGER_ID);

ALTER TABLE OPPHOLD_GRUNNLAG
    ADD COLUMN soning_vurderinger_id BIGINT references SONING_VURDERINGER (ID);