ALTER TABLE brudd_aktivitetsplikt
ALTER COLUMN DOKUMENT_TYPE SET NOT NULL,
ALTER COLUMN DOKUMENT_TYPE SET DEFAULT 'REGISTRERING';


ALTER TABLE brudd_aktivitetsplikt
    ALTER COLUMN DOKUMENT_TYPE DROP DEFAULT;