ALTER TABLE SYKDOM_VURDERING RENAME COLUMN ER_NEDSETTELSE_HOYERE_ENN_NEDRE_GRENSE TO ER_NEDSETTELSE_MER_ENN_HALVPARTEN;
ALTER TABLE SYKDOM_VURDERING DROP COLUMN NEDSATT_ARBEIDSEVNE_DATO;
ALTER TABLE SYKDOM_VURDERING DROP COLUMN NEDRE_GRENSE;
ALTER TABLE SYKDOM_VURDERING
    ADD column ER_NEDSETTELSE_MER_ENN_YRKESSKADE_GRENSE BOOLEAN;
ALTER TABLE SYKDOM_VURDERING
    ADD column ER_NEDSETTELSE_AV_EN_VISS_VARIGHET BOOLEAN;
ALTER TABLE SYKDOM_VURDERING
    ADD column YRKESSKADE_BEGRUNNELSE text;

ALTER TABLE BEREGNINGSTIDSPUNKT_VURDERING
    ADD column NEDSATT_ARBEIDSEVNE_DATO DATE;

ALTER TABLE YRKESSKADE_VURDERING DROP COLUMN SKADEDATO;

CREATE TABLE YRKESSKADE_RELATERTE_SAKER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES YRKESSKADE_VURDERING (ID),
    REFERANSE    VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX UIDX_YRKESSKADE_RELATERTE_SAKER ON YRKESSKADE_RELATERTE_SAKER (REFERANSE, VURDERING_ID);

ALTER TABLE BEREGNINGSTIDSPUNKT_VURDERING RENAME COLUMN BEGRUNNELSE TO NEDSATT_BEGRUNNELSE;
ALTER TABLE BEREGNINGSTIDSPUNKT_VURDERING
    ADD column YTTERLIGERE_NEDSATT_BEGRUNNELSE text;
ALTER TABLE BEREGNINGSTIDSPUNKT_VURDERING DROP COLUMN YRKESSKADE_ANTATT_ARLIG_INNTEKT;

ALTER TABLE BEREGNINGSTIDSPUNKT_GRUNNLAG RENAME TO BEREGNINGSFAKTA_GRUNNLAG;
ALTER TABLE BEREGNINGSFAKTA_GRUNNLAG RENAME COLUMN VURDERING_ID TO TIDSPUNKT_VURDERING_ID;

CREATE TABLE YRKESSKADE_INNTEKTER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BEREGNINGSFAKTA_GRUNNLAG
    ADD column YRKESSKADE_VURDERING_ID BIGINT REFERENCES YRKESSKADE_INNTEKTER;

CREATE TABLE YRKESSKADE_INNTEKT
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    INNTEKTER_ID         BIGINT                                 NOT NULL REFERENCES YRKESSKADE_INNTEKTER (ID),
    REFERANSE            VARCHAR(50)                            NOT NULL,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ANTATT_ARLIG_INNTEKT NUMERIC(19, 2)                         NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_YRKESSKADE_INNTEKT_SAKER ON YRKESSKADE_INNTEKT (REFERANSE, INNTEKTER_ID);