ALTER TABLE SYKDOM_VURDERING RENAME COLUMN ER_NEDSETTELSE_HOYERE_ENN_NEDRE_GRENSE TO ER_NEDSETTELSE_MER_ENN_HALVPARTEN;
ALTER TABLE SYKDOM_VURDERING DROP COLUMN NEDSATT_ARBEIDSEVNE_DATO;
ALTER TABLE SYKDOM_VURDERING DROP COLUMN NEDRE_GRENSE;
ALTER TABLE SYKDOM_VURDERING
    ADD column ER_NEDSETTELSE_MER_ENN_YRKESSKADE_GRENSE BOOLEAN;
ALTER TABLE SYKDOM_VURDERING
    ADD column ER_NEDSETTELSE_AV_EN_VISS_VARIGHET BOOLEAN;
ALTER TABLE SYKDOM_VURDERING
    ADD column YRKESSKADE_BEGRUNNELSE text;

ALTER TABLE BEREGNINGSTIDSPUNKT_VURDERING
    ADD column NEDSATT_ARBEIDSEVNE_DATO DATE;

ALTER TABLE YRKESSKADE_VURDERING DROP COLUMN SKADEDATO;

CREATE TABLE YRKESSKADE_RELATERTE_SAKER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES YRKESSKADE_VURDERING (ID),
    REFERANSE    VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_YRKESSKADE_RELATERTE_SAKER ON YRKESSKADE_RELATERTE_SAKER (REFERANSE, VURDERING_ID);