ALTER TABLE UNDERVEIS_PERIODE
    ALTER COLUMN TIMER_ARBEID SET DEFAULT 0,
    ALTER COLUMN GRADERING SET DEFAULT 0,
    ALTER COLUMN ANDEL_ARBEIDSEVNE SET DEFAULT 0;

ALTER TABLE UNDERVEIS_PERIODE
    ALTER COLUMN TIMER_ARBEID NOT NULL,
    ALTER COLUMN GRADERING NOT NULL,
    ALTER COLUMN ANDEL_ARBEIDSEVNE NOT NULL;